import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;


public class App extends JFrame {
    private JPanel panel1;
    private Map mapPanel;
    private JLabel topLabel;
    private JPanel sideBar;

    public static void main(String[] args) {
        App frame = new App();
        frame.setVisible(true);
        Map map = frame.getMap();
        Timer timer = new Timer();
        BufferedImage plane = null;
        try {
            plane = ImageIO.read(new File("/home/alexm/plane.png"));
        } catch (IOException e) {
            System.out.println("Couldnt find the plane file");
            e.printStackTrace();
        }
        map.planeImage = plane;
        map.planes.add(new Jet(1, 2, 5.0 * Math.PI / 4.0));
        map.planes.add(new Jet(42, 17, 3.0 * Math.PI / 4.0));
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                map.planes.get(0).x++;
                map.planes.get(0).y++;
                map.repaint();
            }
        }, 20, 35);

    }

    public Map getMap() {
        return mapPanel;
    }

    public App() {
        $$$setupUI$$$();
        setTitle("MediaLab flight simulation");
        setSize(1100, 522);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        add(panel1);
        topLabel.setText("Simulated Time: 0 ");

    }

    private void createUIComponents() {
        mapPanel = new Map(960, 480);
        topLabel = new JLabel("Label");
        sideBar = new Sidebar();
        //sideBar.setSize(420, 420);
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        topLabel.setText("Label");
        panel1.add(topLabel, BorderLayout.NORTH);
        panel1.add(sideBar, BorderLayout.EAST);
        panel1.add(mapPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
